import type { Metadata } from "next";
import "@/styles/globals.css";
import { rubik } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${rubik.className} bg-amber-50`}>{children}</body>
    </html>
  );
}
